Repository wecode-bootcamp-korea/11-MagicConch-frontend, pull requests merged in 2020-09, with the labels that each got.

#1 [이상훈]Add: Footer 레이아웃 완성
  package-lock.json
  package.json
  src/Components/Footer/Footer.js
  src/index.js
Labels: Status: Accepted

#3 [이상훈]Add: Nav 레이아웃 완성
  src/Components/Footer/Footer.js
  src/Components/Nav/Nav.js
  src/Components/Nav/Svg.js
  src/Routes.js
  src/Styles/GlobalStyle.js
  src/Styles/ThemeProvider.js
  src/index.js
Labels: Status: 리뷰 요청

#2 [김규영]Modified: Login페이지 구성완료
  src/Pages/Login/Login.js
  src/Pages/Login/LoginInput/Components/CheckBoxWithText.js
  src/Pages/Login/LoginInput/Components/Config.js
  src/Pages/Login/LoginInput/Components/ErrorTextBox.js
  src/Pages/Login/LoginInput/Components/InputComboBox.js
  src/Pages/Login/LoginInput/Components/LoginArticle.js
  src/Pages/Login/LoginInput/Components/LoginDescription.js
  src/Pages/Login/LoginInput/Components/RegisterArticle.js
  src/Pages/Login/LoginInput/Components/RegisterDescription.js
  src/Pages/Login/LoginInput/Components/SignButton.js
  src/Pages/Login/LoginInput/LoginInput.js
Labels: Status: 리뷰 요청

#4 [이효정] Refactor: 2차 멘토 리뷰 반영
  public/data/product.json
  public/data/productIn.json
  src/Components/Footer/Footer.js
  src/Components/Nav/Nav.js
  src/Pages/Cart/Cart.js
  src/Pages/Cart/Component/CartTable.js
  src/Pages/ProductDetail/Component/ProductBox.js
  src/Pages/ProductDetail/Component/ProductModal.js
  src/Pages/ProductDetail/Component/ProductSlider.js
  src/Pages/ProductDetail/Component/ProductSliderIn.js
  src/Pages/ProductDetail/Component/Relatedproducts.js
  src/Pages/ProductDetail/Component/SliderCard.js
  src/Pages/ProductDetail/ProductDetail.js
  src/Pages/ProductList/Component/Category.js
  src/Pages/ProductList/ProductCard.js
  src/Pages/ProductList/ProductComponent.js
  src/Pages/ProductList/ProductList.js
  src/Routes.js
Labels: Status: 리뷰 요청

#6 [이상훈]Add: 메인 레이아웃 완성
  public/data/mainMockdata.json
  src/Components/Footer/Footer.js
  src/Components/Nav/Nav.js
  src/Pages/Main/Main.js
  src/Pages/Main/MainComponents/BackgroundContents.js
  src/Pages/Main/MainComponents/BigCardContents.js
  src/Pages/Main/MainComponents/CardContents.js
  src/Pages/Main/MainComponents/FullSizeContents.js
  src/Pages/Main/MainComponents/ObjectContents.js
  src/Pages/Main/MainComponents/ParagraphContents.js
  src/Pages/Main/MainComponents/PopularContents.js
  src/Pages/Main/MainComponents/SlideCotents.js
  src/Pages/Main/MainComponents/ThreeCardContents.js
  src/Pages/Main/MainComponents/TwoCardContents.js
  src/Styles/ThemeProvider.js
  src/index.js
Labels: Status: 수정 요청

#5 [김규영]Add:리뷰내용반영
  package-lock.json
  package.json
  public/Data/PaymentMethod/CardList.json
  public/Data/manifest.json
  public/Images/MyAccount/amex.svg
  public/Images/MyAccount/diners.svg
  public/Images/MyAccount/discover.svg
  public/Images/MyAccount/jcb.svg
  public/Images/MyAccount/kinfolk.png
  public/Images/MyAccount/mastercard.svg
  public/Images/MyAccount/visa.svg
  src/Pages/Login/Login.js
  src/Pages/Login/LoginInput/Components/Config.js
  src/Pages/MyAccount/Components/AccountDetail/AccountDetail.js
  src/Pages/MyAccount/Components/Address/Address.js
  src/Pages/MyAccount/Components/Category/Category.js
  src/Pages/MyAccount/Components/Dashboard/Dashboard.js
  src/Pages/MyAccount/Components/InputComboBox.js
  src/Pages/MyAccount/Components/Login/Components/CheckBoxWithText.js
  src/Pages/MyAccount/Components/Login/Components/Config.js
  src/Pages/MyAccount/Components/Login/Components/ErrorTextBox.js
  src/Pages/MyAccount/Components/Login/Components/LoginArticle.js
  src/Pages/MyAccount/Components/Login/Components/LoginDescription.js
  src/Pages/MyAccount/Components/Login/Components/RegisterArticle.js
  src/Pages/MyAccount/Components/Login/Components/RegisterDescription.js
  src/Pages/MyAccount/Components/Login/Components/SignButton.js
  src/Pages/MyAccount/Components/Login/Login.js
  src/Pages/MyAccount/Components/Order/Order.js
  src/Pages/MyAccount/Components/PaymentMethod/PaymentMethod.js
  src/Pages/MyAccount/Components/PaymentMethod/RegistCardPage.js
  src/Pages/MyAccount/Components/PaymentMethod/RegistedCardListTable.js
  src/Pages/MyAccount/Components/SignButton.js
  src/Pages/MyAccount/Components/Subsciprtion/Subscription.js
  src/Pages/MyAccount/MyAccount.js
  src/Pages/MyPage/MyPage.js
  src/Routes.js
  src/Styles/common.scss
  yarn.lock
Labels: Status: 수정 요청

#8 [이상훈]Refactor: 불필요한 Hook 수정 완료
  public/data/mainMockdata.json
  src/Components/Button/KinfolkButton.js
  src/Components/Button/QuitButton.js
  src/Components/Nav/CartNav.js
  src/Components/Nav/CategoryNav.js
  src/Components/Nav/LogoScroll.js
  src/Components/Nav/Nav.js
  src/Components/Nav/SearchModal.js
  src/Components/Nav/Svg.js
  src/Pages/Main/Main.js
  src/Pages/Main/MainComponents/CardContents.js
  src/Pages/Main/MainComponents/FullSizeContents.js
  src/Pages/Search/Search.js
  src/Routes.js
Labels: Status: Accepted

#9 [이상훈]Refactor: Search Page 옵셔널 체이닝 등 적용완료
  public/data/mainMockdata.json
  src/Pages/Main/MainComponents/CardContents.js
  src/Pages/Search/Search.js
Labels: Status: 리뷰 요청

#10 [이상훈]Add: Design Page 레이아웃 완성
  public/data/mainMockdata.json
  src/Components/Button/GoNextButton.js
  src/Components/Button/GoPrevButton.js
  src/Components/Footer/Footer.js
  src/Components/Nav/Nav.js
  src/Pages/Design/Design.js
  src/Pages/Main/Main.js
  src/Pages/Main/MainComponents/BackgroundContents.js
  src/Pages/Main/MainComponents/BigCardContents.js
  src/Pages/Main/MainComponents/CardContents.js
  src/Pages/Main/MainComponents/PopularContents.js
  src/Pages/Search/Search.js
  src/Routes.js
Labels: Status: 리뷰 요청

#13 [김규영]Add : 로그인 최종본
  package-lock.json
  package.json
  src/Pages/Cart/Cart.js
  src/Pages/MyAccount/Components/Login/Components/CheckBoxWithText.js
  src/Pages/MyAccount/Components/Login/Components/Config.js
  src/Pages/MyAccount/Components/Login/Components/LoginArticle.js
  src/Pages/MyAccount/Components/Login/Components/RegisterArticle.js
  src/Pages/MyAccount/Components/Login/Components/SignButton.js
  src/Pages/MyAccount/Components/Login/Login.js
  src/Pages/MyAccount/MyAccount.js
  src/Pages/Search/Search.js
Labels: Status: 리뷰 요청
